[project]
name = "architecture"
version = "0.1.0"
description = "Zensical Setup for GIG Cymru Architecture site"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ghp-import>=2.1.0",
    "zensical>=0.0.8",
]
